# language: pt
# encoding: utf-8
Funcionalidade: XX

XXX

Contexto: XXX
- YYY_MASTER_YYY

Dado XXX
E Teste
| Ibagem |
| ![Image](xxx.png) |
| <img src="xxx.png"> |   
| <img src="xxx.png" width="50"> |
| ![Image](https://pt.wikipedia.org/static/images/project-logos/ptwiki.png) |
| Link Html Embeded: [Link Embeded](html_embed.html) |
| Link Google: [Google](https://www.google.com.br) |
| <strike>strike</strike> |
| <strike>strike<br>strike</strike> |


Esquema do Cenário: JJJ
Quando xxx 
E YYY 
Exemplos: 
| a | b | 
| c | d | 